### ISSUE TITLE
DBM postprocessing

### ISSUE THREAD

**Issue by gdevenyi** [CoBrALab/optimized_antsMultivariateTemplateConstruction#16]
Write a script to take the modelbuild input/output directory and produce a DBM
- [x] check that nlin files exist
- [x] use mask if available for important steps
- [x] qbatch submission
- [ ] log and non-log with filenames
- [x] multiple blur options
- [x] better blur default
- [x] common space registration and resampling

**Comment by araikes** [comment]
I'm very interested in the DBM post-processing. If you need someone to test things, let me know.

**Comment by gdevenyi** [comment]
Everything is here! https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction/pull/31

**Comment by gdevenyi** [comment]
@araikes I now have two-level DBM draft implemented at #39

**Comment by araikes** [comment]
@gdevenyi,

Sounds like fun... except I don't have any longitudinal data to take advantage of it. 

Does the interface change at all for cross-sectional data?

**Comment by araikes** [comment]
Also,

I've been using the DBM option for the last couple months and it seems to work without notable issue. Getting down toward manuscripts so hopefully you'll get some citations out of this soon.
