### ISSUE TITLE
Running optimized_antsMultivariateTemplateConstruction without a cluster

### ISSUE THREAD

**Issue by hgellersen** [CoBrALab/optimized_antsMultivariateTemplateConstruction#51]
Hello, I was hoping to use optimized_antsMultivariateTemplateConstruction for one of my research projects but unfortunately, our high-performance computing server does not have a cluster and can therefore not use SLURM/qbatch commands. Is there a way in which optimized_antsMultivariateTemplateConstruction can be used without a cluster? Thanks for any help on this matter.

**Comment by gdevenyi** [comment]
Hi @hgellersen 

This implementation requires a functioning install of https://github.com/pipitone/qbatch, which in turn supports gnu-parallel as a local backend in the case of no cluster.

See the documentation here:
https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction#requirements

**Comment by hgellersen** [comment]
Brilliant, I'll give that a try. Thanks so much!
