### ISSUE TITLE
two-level DBM question

### ISSUE THREAD

**Issue by araikes** [CoBrALab/optimized_antsMultivariateTemplateConstruction#79]
Hi @gdevenyi ,

I have a project I'm consulting on for which the two-level DBM approach is worthwhile. I just want to clarify the outputs. 

From that pipeline, the second-level resampled DBM outputs give one image for each session/time point that encode the absolute or relative deformation to the subject-specific template. Because they are log-Jacobians, subtraction maps wouldn't be appropriate to get change from timepoint to timepoint but putting those into a statistical engine (SPM, FSL's randomise, PALM, etc) using a repeated measures design matrix would enable modeling the within subject slopes as well as group and time point differences (assuming a group x time experiment). 

Is that a correct understanding of the outputs that are produced?

**Comment by gdevenyi** [comment]
> From that pipeline, the second-level resampled DBM outputs give one image for each session/time point that encode the absolute or relative deformation to the subject-specific template.

Correct.

> Because they are log-Jacobians, subtraction maps wouldn't be appropriate

I don't know what a subtraction map is.

> but putting those into a statistical engine (SPM, FSL's randomise, PALM, etc) using a repeated measures design matrix would enable modeling the within subject slopes as well as group and time point differences (assuming a group x time experiment).

Our typical modelling is linear mixed-effect models within-subject (aka repeat measures) in RMINC.
